apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-service
  namespace: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: shamkumbhar47/frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: demo-app
spec:
  type: LoadBalancer   # 🔥 AWS creates ELB / NLB
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
